import type {
  FinancialBill,
  FinancialCategory,
  FinancialTransaction,
} from "@/lib/finance/types";

export const initialCategories: FinancialCategory[] = [
  { id: "cat-sales", name: "Vendas", kind: "income" },
  { id: "cat-services", name: "Servicos", kind: "income" },
  { id: "cat-marketing", name: "Marketing", kind: "expense" },
  { id: "cat-suppliers", name: "Fornecedores", kind: "expense" },
  { id: "cat-payroll", name: "Salarios", kind: "expense" },
  { id: "cat-ops", name: "Operacao", kind: "expense" },
];

export const initialTransactions: FinancialTransaction[] = [
  {
    id: "tx-1",
    kind: "income",
    amount: 12800,
    date: "2026-03-01",
    description: "Vendas do ecommerce",
    categoryId: "cat-sales",
    origin: "Vendas",
  },
  {
    id: "tx-2",
    kind: "income",
    amount: 7600,
    date: "2026-03-06",
    description: "Consultoria mensal",
    categoryId: "cat-services",
    origin: "Servicos",
  },
  {
    id: "tx-3",
    kind: "expense",
    amount: 4200,
    date: "2026-03-05",
    description: "Campanha de performance",
    categoryId: "cat-marketing",
    expenseType: "variable",
  },
  {
    id: "tx-4",
    kind: "expense",
    amount: 9900,
    date: "2026-03-10",
    description: "Folha de pagamento",
    categoryId: "cat-payroll",
    expenseType: "fixed",
  },
  {
    id: "tx-5",
    kind: "expense",
    amount: 3800,
    date: "2026-03-12",
    description: "Compra de insumos",
    categoryId: "cat-suppliers",
    expenseType: "variable",
  },
  {
    id: "tx-6",
    kind: "income",
    amount: 5400,
    date: "2026-02-19",
    description: "Pacote de servicos",
    categoryId: "cat-services",
    origin: "Servicos",
  },
  {
    id: "tx-7",
    kind: "expense",
    amount: 2600,
    date: "2026-02-21",
    description: "Infraestrutura cloud",
    categoryId: "cat-ops",
    expenseType: "fixed",
  },
];

export const initialBills: FinancialBill[] = [
  {
    id: "bill-1",
    title: "Assinatura ERP",
    amount: 890,
    dueDate: "2026-03-18",
    status: "paid",
    kind: "payable",
    categoryId: "cat-ops",
  },
  {
    id: "bill-2",
    title: "Fatura agencia de marketing",
    amount: 3200,
    dueDate: "2026-03-28",
    status: "pending",
    kind: "payable",
    categoryId: "cat-marketing",
  },
  {
    id: "bill-3",
    title: "Recebimento contrato anual",
    amount: 11800,
    dueDate: "2026-04-02",
    status: "pending",
    kind: "receivable",
    categoryId: "cat-services",
  },
  {
    id: "bill-4",
    title: "Pagamento fornecedor A",
    amount: 2500,
    dueDate: "2026-03-08",
    status: "overdue",
    kind: "payable",
    categoryId: "cat-suppliers",
  },
];
